### ISSUE TITLE
Enable auto geo lookup

### ISSUE THREAD

**Issue by Lavaerius** [quadnegative/MorphingClockG#2]
We can leverage a couple of apis innorder to automatically determine location of the board, that should be default behavior

**Comment by quadnegative** [comment]
I actually like the httpclient.
Spin up a new issue to rewrite the getweatherjson to use httpclient...

**Comment by quadnegative** [comment]
This was rolled into PR 23.
https://github.com/quadnegative/MorphingClockG/pull/23
Complete.
